myapp/core/views.py
from flask import render_template, request, Blueprint
from myapp.models import PasswordVault

core = Blueprint('core', __name__)

@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    password_posts = PasswordVault.query.order_by(PasswordVault.date.desc()).paginate(page=page, per_page=100)
    return render_template('index.html', password_posts=password_posts)

myapp/password_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from myapp import db 
from myapp.models import PasswordVault
from myapp.password_posts.forms import PasswordPostForm

password_posts = Blueprint('password_posts', __name__)

@password_posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PasswordPostForm()
    if form.validate_on_submit():
        password_post = PasswordVault(company=form.company.data, user_name=form.user_name.data, pword=form.pword.data, user_id=current_user.id)
        db.session.add(password_post)
        db.session.commit()
        flash('Password Post was Created')
        print('Password Post was created')
        return redirect(url_for('core.index'))
    return render_template('create_password.html', form=form)

# Make sure the password_post_id is an integer!

@password_posts.route('/<int:password_post_id>')
def password_post(password_post_id):
    password_post = PasswordVault.query.get_or_404(password_post_id) 
    return render_template('password.html', company=password_post.company, date=password_post.date, post=password_post)

@password_posts.route('/<int:password_post_id>/update',methods=['GET','POST'])
@login_required
def update(password_post_id):
    password_post = PasswordVault.query.get_or_404(password_post_id)

    if password_post.author != current_user:
        abort(403)

    form = PasswordPostForm()

    if form.validate_on_submit():
        password_post.company = form.company.data
        password_post.user_name = form.user_name.data
        password_post.pword = form.pword.data
        db.session.commit()
        flash('password Post Updated')
        return redirect(url_for('password_posts.password_post',password_post_id=password_post.id))

    elif request.method == 'GET':
        form.company.data = password_post.company
        form.user_name.data = password_post.user_name
        form.pword.data = password_post.pword

    return render_template('create_password.html',title='Updating',form=form)


@password_posts.route('/<int:password_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(password_post_id):

    password_post = PasswordVault.query.get_or_404(password_post_id)
    if password_post.author != current_user:
        abort(403)

    db.session.delete(password_post)
    db.session.commit()
    flash('password Post Deleted')
    return redirect(url_for('core.index'))

myapp/users/views.py
from crypt import methods
from operator import methodcaller
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from myapp import db
from myapp.models import User, PasswordVault
from myapp.users.forms import RegistrationForm, LoginForm, UpdateUserForm

users = Blueprint('users', __name__) # dont forget to register this in __init__.py 


# register
@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration!')
        return redirect(url_for('users.login'))
    
    return render_template('register.html', form=form)

# login
@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index')) #once the user has logged out we will redirect them back home


#account (update UserForm)
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit(): 
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User account updated!!')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('account.html', form=form)

@users.route('/<username>')
def user_passwords(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    password_posts = PasswordVault.query.filter_by(author=user).order_by(PasswordVault.date.desc()).paginate(page=page, per_page=10) 
    return render_template('user_password_posts.html', password_posts=password_posts, user=user)

myapp/templates/account.html
{% extends "base.html" %}
{% block content %}

    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            {{form.hidden_tag()}}
        </div>
        <div class="form-group">
            <div class="accountlabel">{{form.username.label}}:</div>
            {{form.username}}
        </div>
        <div class="form-group">
            <div class="accountlabel">{{form.email.label}}:</div>
            {{form.email}}
        </div>
    
        <div class="form-group">
            {{form.submit(class='update-user-btn')}}
        </div>
    </form>

{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" sizes="32x32" href="../static/images/favicon-32x32.png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <title>Password Vault</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-link">
            <a href="{{url_for('core.index')}}">Passwords</a>
        </li>

        {% if current_user.is_authenticated %}
        <li class="nav-link">
            <a href="{{url_for('password_posts.create_post')}}">Add Password</a> 
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.account')}}">Account</a>
        </li>
        {% else %}
        <li class="nav-link">
            <a href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-link">
            <a href="{{url_for('users.register')}}">Register</a>
        </li>
        {% endif %}
    </ul>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

myapp/templates/create_password.html
{% extends "base.html" %}
{% block content %}
      <form method="POST">
          <div class="form-group">
            {{form.hidden_tag()}}
          </div>

          <div class="form-group">
              <div class="formlabel">{{form.company.label}}:</div>
              {{form.company}}
          </div>
          <div class="form-group">
            <div class="formlabel">{{form.user_name.label}}:</div>
            {{form.user_name}}
          </div>
          <div class="form-group">
            <div class="formlabel">{{form.pword.label}}:</div>
            {{form.pword}}
          </div>
          <div class="form-group">
            {{form.submit(class="add-btn")}}
          </div>
      </form>
{% endblock %}

myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
    <div class="card-container">
        {% for post in password_posts.items %}
            {% if current_user.id == post.user_id %}
                <div class="card">
                    <div>
                        <p class="card-title" ><strong>Company</strong>: {{post.company}}</p>
                        <p class="card-title" ><strong>Username</strong>: {{post.user_name}}</p>
                        <p class="card-title" ><strong>Password</strong>: {{post.pword}}</p>
                    </div>
                    <div>
                        <a class="edit-btn" href="{{url_for('password_posts.password_post', password_post_id=post.id)}}">Edit</a>
                    </div>
                </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <h3>You must have an account to acccess Password Vault</h3>
        {% endif %}
    </div>
{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}
{% block content %}

<form method="POST">
    <div class="form-group">
        {{form.hidden_tag()}}
    </div>
    
    <div class="form-group">
        <div class="loginlabel">{{form.email.label}}:</div>
        {{form.email}}
    </div>
    <div class="form-group">
        <div class="loginlabel">{{form.password.label}}:</div>
        {{form.password}}
    </div>
    <div class="form-group">
        {{form.submit(class='login-user-btn')}}
    </div>
</form>
{% endblock %}

myapp/templates/password.html
{% extends "base.html" %}
{% block content %}

<div classs="password-container">
<div class="card">
  <p class="card-title" ><strong>Company</strong>: {{post.company}}</p>
  <p class="card-title" ><strong>Username</strong>: {{post.user_name}}</p>
  <p class="card-title" ><strong>Password</strong>: {{post.pword}}</p>
</div>
{% if post.author == current_user %}
<div>
  <a class="btn btn-primary btn-sm" href="{{ url_for('password_posts.update', password_post_id=post.id) }}">Update</a>
  <form action="{{ url_for('password_posts.delete_post', password_post_id=post.id) }}" method="POST">
    <input class="delete-btn" type="submit" value="Delete">
  </form>
</div>
{% endif %}

{% endblock content %}

myapp/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <div class="form-group">
        {{form.hidden_tag()}}
    </div>
    <div class="form-group">
        <div class="reglabel">{{form.email.label}}</div>
        {{form.email}}
    </div>
    <div class="form-group">
        <div class="reglabel">{{form.username.label}}</div>
        {{form.username}}
    </div>
    <div class="form-group">
        <div class="reglabel">{{form.password.label}}</div>
        {{form.password}}
    </div>
    <div class="form-group">
        <div class="reglabel">{{form.pass_confirm.label}}</div>
        {{form.pass_confirm}}
    </div>
    <div class="form-group">
        {{form.submit(class='reg-user-btn')}}
    </div>
</form>

{% endblock %}